title: Discord has good UI Design
timezone: Europe/Zurich
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2016-09-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: ...how else would you explain the app ignoring a11y settings?
baseurl: ""
url: https://discordhasgoodui.design
color: "#202225"
